### PR TITLE
Players attack, enemies are their and can die.

### PR DESCRIPTION
**Pull request by CaliberMengsk**
**EDIT: read comment below also

**I think we are to the point where if anyone wanted to create a few levels with the tools we have, you can try. While there is no script to change levels, it wouldn't be hard to add, and if we could get a kind of spiffy little test area with multiple room, it'd be nice to just not be quite so... the same. Shouldn't need to add game or sound managers as they will be brought over from the first room automagically. :D

So there were a lot of small things I did and a few bigger things. You'll have to read all the commits if you want everything, but I'll try to summarize to the best of my ability.

I added the sphere like enemies. They use a dumb ai that just floats them towards the closest player in range if they don't already have a target. Pretty simple, but works, especially for a magically floating ball.

Players can now attack. They attack in all four directions, and it plays a sound when they attack with the sword. These attacks can damage and kill enemies. Right now the spheres only have 1 health, but can have however much you want.

Player gui's now properly update. Health and money is individual and can be changed to support more health (by adding sequential number names to health objects in the gui canvas). They also turn on and off if a player is being played or not. I think I put that in the awake event, so wouldn't work if players join mid game, though that could be fixed by making it a function that's called rather then in the awake. Should probably do that if I haven't, but I'm not gonna look right now.

I updated the gamemanager a bit so that it has the option not to spawn players, so we can set up the game settings on a different screen. This will allow for character select and such, as well, we can replace the default player1/2/3/4 game objects for it to spawn with whatever we want, so we can add however many different "skins" we want, or even players with different abilities, like ranged or magic or something. Future proofing.

Enemies actually use the same status script that the players do. I added a little bit of stuff if I recall right. Mainly I main it where it doesn't require a gui to be attached to it to function. Since when you take damage as a player it updates the gui, enemies don't, THOUGH, we can if we want. What do I mean? Well, we could add hearts or a healthbar above the enemy if we really wanted. Again, future proofing it a bit. Makes the script very reusable. 

I think that's mostly it. I did change the level a little (adding in sphere bad guys, and allowing you to now walk into the door, not that it does anything at the moment.)

I think that's pretty much everything. To be honest, I am not sure where I updated last, so this may be describing a few things I did in the last pull request. Anyway, Enjoy. :D

### CODE REVIEW

**Comment by CaliberMengsk** [comment]
OH! Also should note!!! This was with unity 5.2.2, which required updating the unit testing system. Had to remove a dll and update the other to get it to work since unity now includes the first dll with it.

**Comment by CaliberMengsk** [comment]
-_- ignore this one, accidentally tried to pull the wrong branch.

**Comment by SuperWes** [comment]
Sweet dude! Can you bring your computer tonight?

**Comment by CaliberMengsk** [comment]
I have it loaded on my windows tablet, and it's in my pocket, with the mini-hdmi to hdmi adapter, an hdmi cable, and my xbox controller. As stated in the comments though, don't use this pull request as the main branch is extremely old, and I accidentally selected it. (Randy branch is newest, I don't know where the main branch even came from.)

**Pull request closed without merging**
